Bootstrap: docker
From: ghcr.io/liampattinson/epoch:0.2

%help

    This is a Singularity container for running Epoch. It contains several
    Epoch installations for 1D, 2D, and 3D, and variations with different
    combinations of compiler flags switched on.

    Before running Epoch via this container, first load the Singularity and
    OpenMPI modules:

        module load tools/Singularity mpi/OpenMPI

    It can then be run using:

         mpirun -n <nprocs> singularity exec <img> run_epoch.sh <exe> <outdir>

    The parts in <angle brackets> must be filled in by you:

        - <nprocs>: The number of MPI processes to run on. This should be
          set to "${SLURM_NTASKS}" in most cases.
        - <img>: The Singularity image file, or the URI of an uploaded
          image.
        - <exe>: The executable to run. These are defined inside the
          container, so won't be visible on your host system. The
          executables include:
            - epoch1d
            - epoch2d
            - epoch3d
            - epoch1d_qed
            - epoch2d_qed
            - epoch3d_qed
          The 'qed' executables have been compiled with the PHOTONS flag
          switched on. 
        - <outdir>: The directory to write results to. If we want to write
          to the current directory, this can just be '.'. Your "input.deck"
          files should be located here.

    To look around inside the container, try:

        singularity run <img>

    The Epoch repository can be located in the /epoch directory.

    An example sbatch script might look like:

        #!/bin/bash
        #SBATCH --job-name=singularity_epoch         # Job name
        #SBATCH --mail-type=END,FAIL                 # Mail events (NONE, BEGIN, END, FAIL, ALL)
        #SBATCH --mail-user=usr501@york.ac.uk        # Where to send mail
        #SBATCH --ntasks=2                           # Run n tasks...
        #SBATCH --cpus-per-task=1                    # ...with one core each
        #SBATCH --mem-per-cpu=1gb                    # Memory per processor
        #SBATCH --time=00:05:00                      # Time limit hrs:min:sec
        #SBATCH --output=singularity_epoch_%j.log    # Standard output and error log
        #SBATCH --account=my_proj_account            # Project account
         
        module purge
        module load mpi/OpenMPI tools/Singularity
        mpiexec -n ${SLURM_NTASKS} singularity exec epoch.sif run_epoch.sh epoch2d .

    Make sure you have your deck in the output directory with the name "input.deck"
	    
%environment

    export PATH="$PATH:/app/epoch/bin"

%post

    # Docker runs as root, but Singularity runs as user.
    # Need to add user permissions to working folder

    chmod --recursive 755 /app/epoch/bin

%runscript

    # When using 'singularity run', opens interactive shell
    # To run epoch, always use 'singularity exec' instead!

    /bin/bash
