name: Publish Docker/Singularity Images

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/plasmafair/epoch

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: LiamPattinson
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-singularity:
    runs-on: ubuntu-latest
    needs: publish-docker
    container:
      quay.io/singularity/singularity:v3.11.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build container
        run: |
          sudo -E singularity build container.sif Singularity

      - name: Publish container
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | singularity remote login -u LiamPattinson --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/plasmafair/epoch.sif:${{ github.ref_name }}

