name: Test Container Utils

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  run_tests:
    name: Run epoch_container_utils tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install
      working-directory: ./Docker/epoch_container_utils
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Test
      working-directory: ./Docker/epoch_container_utils
      run: |
        pytest -vv
